apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-gateway-https-redirect
spec:
  hostnames:
    - "*.balutoiu.com"
  parentRefs:
    - name: traefik-gateway
      sectionName: web
  rules:
    - filters:
        - requestRedirect:
            port: 443
            scheme: https
            statusCode: 301
          type: RequestRedirect
      matches:
        - path:
            type: PathPrefix
            value: /
