---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-wildcard-balutoiu-com
spec:
  secretName: le-wildcard-balutoiu-com-tls
  dnsNames:
    - "balutoiu.com"
    - "*.balutoiu.com"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
