{{- $fullname := include "external-secrets.fullname" . -}}
{{- range .Values.secrets }}
{{- $common_external_secret_id := default "" .external_secret_id }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default $fullname .name }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
    {{- with .labels }}
      {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
spec:
  secretStoreRef:
    name: {{ $.Values.store.name }}
    kind: {{ $.Values.store.kind }}
  target:
  {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  data:
  {{- range .data }}
  - secretKey: {{ .secret_key }}
    remoteRef:
      key: {{ default .external_secret_id $common_external_secret_id | quote }}
      property: {{ default .secret_key .external_secret_key | quote }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  {{- end }}
{{- end }}
