config:
  address: "10.119.10.90"

# Check https://kube-vip.io/docs/installation/flags/
env:
  cp_enable: "true"
  cp_namespace: "kube-system"
  dns_mode: "first"
  lb_enable: "true"
  lb_port: "6443"
  prometheus_server: ":2112"
  svc_election: "false"
  svc_enable: "true"
  svc_leasename: "plndr-svcs-lock"
  vip_arp: "true"
  vip_interface: "br0"
  vip_leaderelection: "true"
  vip_leaseduration: "5"
  vip_leasename: "plndr-cp-lock"
  vip_renewdeadline: "3"
  vip_retryperiod: "1"
  vip_subnet: "32"

envValueFrom:
  vip_nodename:
    fieldRef:
      fieldPath: spec.nodeName

resources:
  requests:
    cpu: 17m
    memory: 77Mi
  limits:
    memory: 77Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
