secrets:
  - name: argocd-secret
    external_secret_id: K3s-Ceplea Argo CD Secrets
    data:
      - secret_key: admin.password
      - secret_key: admin.passwordMtime
      - secret_key: dex.authelia.oidc.clientSecret
      - secret_key: server.secretkey
      - secret_key: webhook.github.secret
      - secret_key: webhook.gitlab.secret

  - name: helm-secrets-private-keys
    external_secret_id: K3s-Ceplea Helm Secrets Private Keys
    data:
      - secret_key: age-private-keys.txt

  - name: argocd-repo-ionutbalutoiu-home-k8s-private
    external_secret_id: K3s-Ceplea Argo CD Repo - ionutbalutoiu-home-k8s-private
    labels:
      argocd.argoproj.io/secret-type: repository
    data:
      - secret_key: name
      - secret_key: url

  - name: argocd-repo-creds-ionutbalutoiu-home-k8s-private-ssh-creds
    labels:
      argocd.argoproj.io/secret-type: repo-creds
    data:
      - external_secret_id: K3s-Ceplea Argo CD Repo - ionutbalutoiu-home-k8s-private SSH Key
        secret_key: sshPrivateKey
      - external_secret_id: K3s-Ceplea Argo CD Repo - ionutbalutoiu-home-k8s-private
        secret_key: url
