secrets:
  - name: op-credentials
    external_secret_id: K8s Credentials File Base64
    data:
      - secret_key: 1password-credentials.json
        external_secret_key: 1password-credentials.json.base64
