config:
  gitCommitUser: balutoiu-bot
  gitCommitMail: balutoiubot@gmail.com
  gitCommitTemplate: |
    build: automatic update of {{ .AppName }}

    {{ range .AppChanges -}}
    * updates image {{ .Image }} tag `{{ .OldTag }}` to `{{ .NewTag }}`
    {{ end -}}

resources:
  requests:
    memory: 130Mi
    cpu: 25m
  limits:
    memory: 130Mi

ingress:
  enabled: false
