secrets:
  - external_secret_id: Alertmanager - Secrets
    name: monitoring-mimir-alertmanager-secrets
    data:
      - secret_key: DISCORD_ALERTS_WEBHOOK_URL
      - secret_key: DISCORD_ALERTS_BUC_WEBHOOK_URL

  - external_secret_id: Mimir - S3 Creds
    name: monitoring-mimir-s3-creds
    data:
      - secret_key: AWS_ACCESS_KEY_ID
      - secret_key: AWS_SECRET_ACCESS_KEY
