secrets:
  - name: k3s-etcd-snapshot-s3-config
    external_secret_id: "K3s-Ceplea Backup S3 Creds"
    template:
      type: etcd.k3s.cattle.io/s3-config-secret
    data:
      - secret_key: etcd-s3-endpoint
      - secret_key: etcd-s3-access-key
      - secret_key: etcd-s3-secret-key
      - secret_key: etcd-s3-bucket
      - secret_key: etcd-s3-region
