secrets:
  - name: external-secrets-onepassword-connect-k8s-access-token
    external_secret_id: "K8s Access Token: Kubernetes"
    data:
      - secret_key: token
        external_secret_key: credential
