secrets:
  - name: immich-db-backup-s3-creds
    external_secret_id: DB Backup S3 Creds - Immich
    data:
      - secret_key: ACCESS_KEY_ID
      - secret_key: SECRET_ACCESS_KEY
      - secret_key: REGION
