groupName: acme.balutoiu.com

issuers:
  - name: le-prod
    create: true
    kind: ClusterIssuer
    cnameStrategy: None
    acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
    email: ionutbalutoiu@gmail.com
    ovhEndpointName: ovh-eu
    ovhAuthenticationMethod: application
    ovhAuthenticationRef:
      applicationKeyRef:
        name: cert-manager-webhook-ovh-app-creds
        key: applicationKey
      applicationSecretRef:
        name: cert-manager-webhook-ovh-app-creds
        key: applicationSecret
      applicationConsumerKeyRef:
        name: cert-manager-webhook-ovh-app-creds
        key: consumerKey
    externalAccountBinding:
      enabled: false
      keyID: ''
      keySecretRef:
        name: ''
        key: ''

pod:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
    limits:
      memory: 128Mi
