secrets:
  - name: external-dns-ovh-app-creds
    external_secret_id: External-DNS OVH App Creds
    data:
      - secret_key: OVH_APPLICATION_KEY
      - secret_key: OVH_APPLICATION_SECRET
      - secret_key: OVH_CONSUMER_KEY
