secrets:
  - name: cert-manager-webhook-ovh-app-creds
    external_secret_id: Cert-Manager OVH App Creds
    data:
      - secret_key: applicationKey
      - secret_key: applicationSecret
      - secret_key: consumerKey
