secrets:
  - name: cert-manager-webhook-ovh-app-creds
    onepassword_secret_title: Cert-Manager OVH App Creds
    data:
      - secret_key: applicationKey
      - secret_key: applicationSecret
      - secret_key: consumerKey
