secrets:
  - name: backup-rclone-conf
    external_secret_id: Restic Backups rclone.conf
    data:
      - secret_key: rclone.conf

  - name: backup-restic-password
    external_secret_id: Restic Backups Encryption Password
    data:
      - secret_key: restic-password
