secrets:
  - name: garm-secrets
    external_secret_id: K3s-Ceplea GARM
    data:
      - secret_key: JWT
      - secret_key: DB_PASSPHRASE

  - name: garm-lxd-certs
    data:
      - external_secret_id: K3s-Ceplea GARM LXD - server.crt
        secret_key: server.crt
      - external_secret_id: K3s-Ceplea GARM LXD - client.crt
        secret_key: client.crt
      - external_secret_id: K3s-Ceplea GARM LXD - client.key
        secret_key: client.key
