---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-buc-balutoiu-com
spec:
  endpoints:
    - dnsName: "*.internal.buc.balutoiu.com"
      recordType: A
      targets:
        - 10.130.11.90
