apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-wildcard-internal-buc-balutoiu-com
spec:
  secretName: le-wildcard-internal-buc-balutoiu-com-tls
  dnsNames:
    - "*.internal.buc.balutoiu.com"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
