secrets:
  - name: headlamp-oidc
    external_secret_id: K3s-Ceplea Headlamp OIDC
    data:
      - secret_key: OIDC_CLIENT_ID
      - secret_key: OIDC_CLIENT_SECRET
      - secret_key: OIDC_ISSUER_URL
      - secret_key: OIDC_SCOPES
      - secret_key: OIDC_USE_PKCE
