secrets:
  - name: wg-proxy-peer-conf
    external_secret_id: WireGuard - peer CepleaFrigate
    data:
      - secret_key: peer_CepleaFrigate.conf

  - name: frigate-secrets
    external_secret_id: K3s-Ceplea Frigate Secrets
    data:
      - secret_key: FRIGATE_CEPLEA_POARTA_USER
      - secret_key: FRIGATE_CEPLEA_POARTA_PASSWORD

      - secret_key: FRIGATE_CEPLEA_POARTA_TATAIE_USER
      - secret_key: FRIGATE_CEPLEA_POARTA_TATAIE_PASSWORD

      - secret_key: FRIGATE_CEPLEA_TATAIE_GAINI_USER
      - secret_key: FRIGATE_CEPLEA_TATAIE_GAINI_PASSWORD

      - secret_key: FRIGATE_CEPLEA_CURTE_FATA_USER
      - secret_key: FRIGATE_CEPLEA_CURTE_FATA_PASSWORD

      - secret_key: FRIGATE_CEPLEA_CURTE_SPATE_USER
      - secret_key: FRIGATE_CEPLEA_CURTE_SPATE_PASSWORD

      - secret_key: FRIGATE_CEPLEA_GRADINA_USER
      - secret_key: FRIGATE_CEPLEA_GRADINA_PASSWORD

      - secret_key: FRIGATE_FLORESTI_POARTA_USER
      - secret_key: FRIGATE_FLORESTI_POARTA_PASSWORD

      - secret_key: FRIGATE_FLORESTI_CURTE_FATA_USER
      - secret_key: FRIGATE_FLORESTI_CURTE_FATA_PASSWORD

      - secret_key: FRIGATE_FLORESTI_GAINI_USER
      - secret_key: FRIGATE_FLORESTI_GAINI_PASSWORD
