preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

defaultSettings:
  fastReplicaRebuildEnabled: true
  snapshotDataIntegrity: enabled
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
  snapshotDataIntegrityCronjob: "0 3 * * *"

image:
  longhorn:
    instanceManager:
      tag: v1.11.0-hotfix-1
    manager:
      tag: v1.11.0-hotfix-1

persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Delete

ingress:
  enabled: true
  host: longhorn.internal.balutoiu.com
  ingressClassName: traefik-internal

metrics:
  serviceMonitor:
    enabled: true

defaultBackupStore:
  backupTarget: s3://longhorn-backups@garage/
  backupTargetCredentialSecret: longhorn-backups-s3-creds
