secrets:
  - name: longhorn-backups-s3-creds
    external_secret_id: Longhorn Backups S3 Creds
    data:
      - secret_key: AWS_ACCESS_KEY_ID
      - secret_key: AWS_SECRET_ACCESS_KEY
      - secret_key: AWS_ENDPOINTS
