secrets:
  - name: monitoring-grafana-admin-credentials
    external_secret_id: K3s-Ceplea Grafana Secrets
    data:
      - secret_key: ADMIN_USER
      - secret_key: ADMIN_PASSWORD

  - name: monitoring-grafana-authelia-auth
    external_secret_id: K3s-Ceplea Grafana Secrets
    data:
      - secret_key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      - secret_key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
